### ISSUE TITLE
4th Argument (searchPath)

### ISSUE THREAD

**Issue by tdurieux** [AutoProRepair/LSRepair#1]
Hi @BruceKuiLiu,

I'm trying to use your repair tools but I face a problem to setup the arguments.

What should I provide for the 4th arguement:

https://github.com/AutoProRepair/LSRepair/blob/53fa15a828fb89494d464757de60600e3bb011ae/LSRepair/src/main/java/live/search/main/MainProcess.java#L30

Thank you

**Comment by Kui-Liu** [comment]
Yes, you need to provide the 4th argument for it.

The data for 4th argument can be done by DataPreparer.
